### ISSUE TITLE
Problem when installing the Drone CLI

### ISSUE THREAD

**Issue by BenoitSen** [drone-os/drone#2] opened 2020-02-14 16:31 UTC
When running the command `cargo +nightly install drone` from the Drone book, there is an error when compiling drone v0.11.1 :

```
error[E0061]: this function takes 1 parameter but 0 parameters were supplied
  --> src/heap/trace.rs:71:33
   |
71 |         match self.gen.as_mut().resume() {
   |                                 ^^^^^^
   |
help: expected the unit value `()`; create it with empty parentheses
   |
71 |         match self.gen.as_mut().resume(()) {
   |                                        ^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0061`.
```
When applying the change suggested, the command works fine.

**Comment by thibautvdv** [comment] 2020-02-26 11:59
The installation instruction in the README should maybe be: 
`cargo +nightly-2019-11-06 install drone` to work without #3 .

**Comment by valff** [comment] 2020-02-28 19:13
Thanks for the report. There is Drone 0.12 version coming soon with support for newer nightlies. The issue caused by landing the generator resume arguments feature. This is a long-waited feature that allows us to get rid of `libcore-drone` wrapper. So a new breaking release is needed.

**Comment by rmja** [comment] 2021-01-23 14:52
@valff I think we can close this one. This issue is not present anymore as far as I can tell.

**Comment by valff** [comment] 2021-02-22 16:47
Right, closing this.

**Closed by valff** 2021-02-22 16:47 UTC
